### ISSUE TITLE
Mention when linking github issues.

### ISSUE THREAD

**Issue by Timshel** [meixger/hackernews-daily#311]
Hey,

Nice use of the workflows :).
But you might have missed that if the link is a Github Issue then a mention will be added to it.
Cf "Mozilla Standards Position ..." in https://github.com/meixger/hackernews-daily/issues/310.

Which is kind of spammy especially if peoples start to fork it.

**Comment by meixger** [comment]
Yes, you are right.

I'll try if omitting the `www` from the link (as mentioned [here](https://github.com/orgs/community/discussions/23123)) will avoid creating a reference.
